server:
  port: 8888

spring:
  cloud:
    gateway:
      routes:
        - id: produit
          uri: http://localhost:8080
          predicates:
            - Path= /produits/**
        - id: facture
          uri: http://localhost:8081
          predicates:
            - Path= /factures/**
        - id: aggregate
          uri: http://localhost:8082
          predicates:
            - Path= /facturesdetaillees/**